version: '3.8'

services:
  passkeep-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: passkeep-1
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /user/src/app/node_modules
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
